[plugin]
repository = "https://github.com/MidoriKami/MiniCactpotSolver.git"
owners = [ "daemitus", "MidoriKami" ]
project_path = "MiniCactpotSolver"
commit = "1464a469275b666935f2f2deda9a1fa3f37286f3"
