[plugin]
repository = "https://github.com/MidoriKami/WondrousTailsSolver.git"
owners = [ "daemitus", "MidoriKami" ]
project_path = "WondrousTailsSolver"
commit = "a23c2bfa74217d659dc43770f730102439dbd361"
changelog = ""
